image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --build-arg "COMMIT=$CI_COMMIT_SHA" --build-arg "VERSION=$CI_COMMIT_REF_NAME" --pull -t "$CI_REGISTRY_IMAGE" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  only:
    - tags

deploy:
  image: alpine
  stage: deploy
  environment:
    name: production
    url: https://gont.ch
  before_script:
    - wget -qO /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.15.1/bin/linux/amd64/kubectl
    - wget -qO /usr/local/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.0.2/kustomize_3.0.2_linux_amd64
    - chmod +x /usr/local/bin/kubectl /usr/local/bin/kustomize
  script:
    - cd k8s
    - kustomize edit set image trifid=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - kustomize build | kubectl apply -f -
  only:
    - tags
