apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: trifid
  app.kubernetes.io/instance: gont.ch

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
